// ── Tree Tiers ──────────────────────────────────────────────
export const TREE_TIERS = [
  { id: 1, name: 'Seedling',    growTime: 30, yieldMin: 1, yieldMax: 2, unlockCost: 0 },
  { id: 2, name: 'Young Tree',  growTime: 25, yieldMin: 2, yieldMax: 3, unlockCost: 500 },
  { id: 3, name: 'Mature Tree', growTime: 20, yieldMin: 3, yieldMax: 5, unlockCost: 2000 },
  { id: 4, name: 'Ancient Tree',growTime: 15, yieldMin: 5, yieldMax: 8, unlockCost: 8000 },
];

// ── Ingredients ─────────────────────────────────────────────
export const INGREDIENTS = {
  water:        { name: 'Water',        price: 0 },
  sugar:        { name: 'Sugar',        price: 2 },
  tomato:       { name: 'Tomato',       price: 3 },
  onion:        { name: 'Onion',        price: 2 },
  milk:         { name: 'Milk',         price: 4 },
  cream:        { name: 'Cream',        price: 5 },
  rice:         { name: 'Rice',         price: 3 },
  coconutMilk:  { name: 'Coconut Milk', price: 5 },
  redBean:      { name: 'Red Bean',     price: 4 },
  shavedIce:    { name: 'Shaved Ice',   price: 3 },
};

// ── Products / Recipes ───────────────────────────────────────
export const PRODUCTS = [
  {
    id: 'fresh_mango',
    name: 'Fresh Mango',
    emoji: '🥭',
    mangos: 1,
    ingredients: {},
    craftTime: 0,
    baseSell: 5,
    unlocked: true,
  },
  {
    id: 'mango_juice',
    name: 'Mango Juice',
    emoji: '🧃',
    mangos: 2,
    ingredients: { water: 1 },
    craftTime: 10,
    baseSell: 20,
    unlocked: true,
  },
  {
    id: 'mango_salsa',
    name: 'Mango Salsa',
    emoji: '🫙',
    mangos: 3,
    ingredients: { tomato: 1, onion: 1 },
    craftTime: 15,
    baseSell: 35,
    unlocked: true,
  },
  {
    id: 'mango_smoothie',
    name: 'Mango Smoothie',
    emoji: '🥤',
    mangos: 2,
    ingredients: { milk: 1 },
    craftTime: 12,
    baseSell: 28,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_1',
  },
  {
    id: 'mango_jam',
    name: 'Mango Jam',
    emoji: '🍯',
    mangos: 4,
    ingredients: { sugar: 2 },
    craftTime: 25,
    baseSell: 60,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_1',
  },
  {
    id: 'dried_mango',
    name: 'Dried Mango',
    emoji: '🟠',
    mangos: 3,
    ingredients: {},
    craftTime: 40,
    baseSell: 55,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_2',
  },
  {
    id: 'mango_sticky_rice',
    name: 'Mango Sticky Rice',
    emoji: '🍚',
    mangos: 3,
    ingredients: { rice: 1, coconutMilk: 1 },
    craftTime: 35,
    baseSell: 75,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_2',
  },
  {
    id: 'mango_ice_cream',
    name: 'Mango Ice Cream',
    emoji: '🍦',
    mangos: 4,
    ingredients: { cream: 1, sugar: 1 },
    craftTime: 45,
    baseSell: 90,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_3',
  },
  {
    id: 'mango_bingsoo',
    name: 'Mango Bingsoo',
    emoji: '🍧',
    mangos: 5,
    ingredients: { shavedIce: 1, redBean: 1 },
    craftTime: 50,
    baseSell: 120,
    unlocked: false,
    unlockUpgrade: 'kitchen_recipes_3',
  },
];

// ── Upgrades ─────────────────────────────────────────────────
export const UPGRADES = [
  // ── Farm ──
  {
    id: 'farm_expand_1',
    category: 'farm',
    name: 'Expand Farm I',
    desc: 'Unlock 3×2 plot grid (6 plots)',
    cost: 200,
    requires: null,
    effect: { type: 'farm_size', cols: 3, rows: 2 },
  },
  {
    id: 'farm_expand_2',
    category: 'farm',
    name: 'Expand Farm II',
    desc: 'Unlock 3×3 plot grid (9 plots)',
    cost: 800,
    requires: 'farm_expand_1',
    effect: { type: 'farm_size', cols: 3, rows: 3 },
  },
  {
    id: 'farm_expand_3',
    category: 'farm',
    name: 'Expand Farm III',
    desc: 'Unlock 4×4 plot grid (16 plots)',
    cost: 3000,
    requires: 'farm_expand_2',
    effect: { type: 'farm_size', cols: 4, rows: 4 },
  },
  {
    id: 'farm_expand_4',
    category: 'farm',
    name: 'Expand Farm IV',
    desc: 'Unlock 5×5 plot grid (25 plots)',
    cost: 10000,
    requires: 'farm_expand_3',
    effect: { type: 'farm_size', cols: 5, rows: 5 },
  },
  {
    id: 'farm_tree_2',
    category: 'farm',
    name: 'Young Tree Seed',
    desc: 'Unlock Young Tree tier (25s, 2–3 yield)',
    cost: 500,
    requires: null,
    effect: { type: 'unlock_tier', tier: 2 },
  },
  {
    id: 'farm_tree_3',
    category: 'farm',
    name: 'Mature Tree Seed',
    desc: 'Unlock Mature Tree tier (20s, 3–5 yield)',
    cost: 2000,
    requires: 'farm_tree_2',
    effect: { type: 'unlock_tier', tier: 3 },
  },
  {
    id: 'farm_tree_4',
    category: 'farm',
    name: 'Ancient Tree Seed',
    desc: 'Unlock Ancient Tree tier (15s, 5–8 yield)',
    cost: 8000,
    requires: 'farm_tree_3',
    effect: { type: 'unlock_tier', tier: 4 },
  },
  {
    id: 'farm_wither_grace',
    category: 'farm',
    name: 'Patience Spell',
    desc: 'Wither timer extends to 3× grow time',
    cost: 600,
    requires: null,
    effect: { type: 'wither_multiplier', value: 3 },
  },
  {
    id: 'farm_auto_harvest',
    category: 'farm',
    name: 'Auto-Harvest',
    desc: 'Plots harvest automatically when ready',
    cost: 5000,
    requires: 'farm_expand_2',
    effect: { type: 'auto_harvest' },
  },

  // ── Water ──
  {
    id: 'water_charges_1',
    category: 'water',
    name: 'Bigger Can I',
    desc: 'Water can holds 5 charges',
    cost: 300,
    requires: null,
    effect: { type: 'water_max', value: 5 },
  },
  {
    id: 'water_charges_2',
    category: 'water',
    name: 'Bigger Can II',
    desc: 'Water can holds 8 charges',
    cost: 1200,
    requires: 'water_charges_1',
    effect: { type: 'water_max', value: 8 },
  },
  {
    id: 'water_refill_1',
    category: 'water',
    name: 'Quick Refill I',
    desc: 'Refill rate: 1 charge / 14s',
    cost: 400,
    requires: null,
    effect: { type: 'water_refill', value: 14 },
  },
  {
    id: 'water_refill_2',
    category: 'water',
    name: 'Quick Refill II',
    desc: 'Refill rate: 1 charge / 8s',
    cost: 1500,
    requires: 'water_refill_1',
    effect: { type: 'water_refill', value: 8 },
  },
  {
    id: 'water_auto',
    category: 'water',
    name: 'Auto-Water',
    desc: 'Water applies automatically to all plots',
    cost: 6000,
    requires: 'water_charges_2',
    effect: { type: 'auto_water' },
  },

  // ── Kitchen ──
  {
    id: 'kitchen_queue_2',
    category: 'kitchen',
    name: 'Second Burner',
    desc: 'Craft 2 recipes simultaneously',
    cost: 700,
    requires: null,
    effect: { type: 'craft_slots', value: 2 },
  },
  {
    id: 'kitchen_queue_3',
    category: 'kitchen',
    name: 'Third Burner',
    desc: 'Craft 3 recipes simultaneously',
    cost: 2500,
    requires: 'kitchen_queue_2',
    effect: { type: 'craft_slots', value: 3 },
  },
  {
    id: 'kitchen_speed_1',
    category: 'kitchen',
    name: 'Faster Knife I',
    desc: 'Craft times 20% shorter',
    cost: 900,
    requires: null,
    effect: { type: 'craft_speed', value: 0.8 },
  },
  {
    id: 'kitchen_speed_2',
    category: 'kitchen',
    name: 'Faster Knife II',
    desc: 'Craft times 40% shorter',
    cost: 3000,
    requires: 'kitchen_speed_1',
    effect: { type: 'craft_speed', value: 0.6 },
  },
  {
    id: 'kitchen_recipes_1',
    category: 'kitchen',
    name: 'Recipe Book I',
    desc: 'Unlock Smoothie & Jam recipes',
    cost: 400,
    requires: null,
    effect: { type: 'unlock_recipes', ids: ['mango_smoothie', 'mango_jam'] },
  },
  {
    id: 'kitchen_recipes_2',
    category: 'kitchen',
    name: 'Recipe Book II',
    desc: 'Unlock Dried Mango & Sticky Rice',
    cost: 1500,
    requires: 'kitchen_recipes_1',
    effect: { type: 'unlock_recipes', ids: ['dried_mango', 'mango_sticky_rice'] },
  },
  {
    id: 'kitchen_recipes_3',
    category: 'kitchen',
    name: 'Recipe Book III',
    desc: 'Unlock Ice Cream & Bingsoo',
    cost: 4000,
    requires: 'kitchen_recipes_2',
    effect: { type: 'unlock_recipes', ids: ['mango_ice_cream', 'mango_bingsoo'] },
  },
  {
    id: 'kitchen_auto_craft',
    category: 'kitchen',
    name: 'Auto-Craft',
    desc: 'Re-queues last recipe automatically',
    cost: 8000,
    requires: 'kitchen_queue_2',
    effect: { type: 'auto_craft' },
  },

  // ── Market ──
  {
    id: 'market_price_1',
    category: 'market',
    name: 'Better Stall I',
    desc: 'All sell prices +10%',
    cost: 600,
    requires: null,
    effect: { type: 'price_bonus', value: 1.1 },
  },
  {
    id: 'market_price_2',
    category: 'market',
    name: 'Better Stall II',
    desc: 'All sell prices +20%',
    cost: 2000,
    requires: 'market_price_1',
    effect: { type: 'price_bonus', value: 1.2 },
  },
  {
    id: 'market_price_3',
    category: 'market',
    name: 'Premium Stall',
    desc: 'All sell prices +30%',
    cost: 6000,
    requires: 'market_price_2',
    effect: { type: 'price_bonus', value: 1.3 },
  },
  {
    id: 'market_event_notify',
    category: 'market',
    name: 'Market Gossip',
    desc: 'Market events announced 30s early',
    cost: 1000,
    requires: null,
    effect: { type: 'event_notify' },
  },
  {
    id: 'market_auto_buy',
    category: 'market',
    name: 'Auto-Restock',
    desc: 'Ingredients bought automatically when low',
    cost: 3500,
    requires: 'market_price_1',
    effect: { type: 'auto_buy' },
  },

  // ── Garden Decor (cosmetic) ──
  {
    id: 'decor_flowers',
    category: 'decor',
    name: 'Garden Flowers',
    desc: 'Pretty flowers around the farm 🌸',
    cost: 300,
    requires: null,
    effect: { type: 'cosmetic', key: 'flowers' },
  },
  {
    id: 'decor_signs',
    category: 'decor',
    name: 'Wooden Signs',
    desc: 'Cute signs label each plot 🪧',
    cost: 400,
    requires: null,
    effect: { type: 'cosmetic', key: 'signs' },
  },
  {
    id: 'decor_path',
    category: 'decor',
    name: 'Stone Path',
    desc: 'A winding stone path through the garden 🪨',
    cost: 700,
    requires: 'decor_flowers',
    effect: { type: 'cosmetic', key: 'path' },
  },
  {
    id: 'decor_fountain',
    category: 'decor',
    name: 'Fountain',
    desc: 'A lovely fountain in the center ⛲',
    cost: 2000,
    requires: 'decor_path',
    effect: { type: 'cosmetic', key: 'fountain' },
  },
];

// ── Market Config ────────────────────────────────────────────
export const MARKET = {
  demandFluctuationRange: 0.2,   // ±20%
  demandUpdateInterval: 60,      // seconds
  eventInterval: 300,            // seconds between market events
  eventDuration: 30,             // seconds event lasts
  eventMultiplier: 2,            // price multiplier during event
};

// ── Save Defaults ────────────────────────────────────────────
export const DEFAULT_STATE = {
  coins: 0,
  plots: [
    { state: 'empty', tier: 1, progress: 0, watered: false },
    { state: 'empty', tier: 1, progress: 0, watered: false },
    { state: 'empty', tier: 1, progress: 0, watered: false },
    { state: 'empty', tier: 1, progress: 0, watered: false },
  ],
  farmCols: 2,
  farmRows: 2,
  waterCharges: 3,
  waterMax: 3,
  waterRefillRate: 20,
  waterRefillAccum: 0,
  craftSlots: 1,
  craftQueue: [],
  craftSpeedMult: 1.0,
  autoCraft: false,
  lastCraftRecipe: null,
  inventory: {},
  ingredients: {},
  upgrades: [],
  unlockedTiers: [1],
  unlockedRecipes: ['fresh_mango', 'mango_juice', 'mango_salsa'],
  priceBonus: 1.0,
  demandFactors: {},
  marketEventActive: false,
  marketEventProduct: null,
  marketEventEnds: 0,
  cosmetics: [],
  stats: {
    mangosHarvested: 0,
    productsCrafted: {},
    coinsEarned: 0,
    playtime: 0,
    milestones: [],
  },
  lastSaveTime: 0,
};
